### ISSUE TITLE
Lukitus jää päälle

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1955]
In GitLab by @Smibu on Sep 8, 2020, 14:46

Tällaisia poikkeuksia rupesi tulemaan solkenaan Vesalle 8.9.2020 14:05 luennon aikana:

```
Exception happened on 2020-09-08 11:35:47.649089+00:00 at https://tim.jyu.fi/getUpdates?b=6447&c=1951&d=234824&m=t&q=t

vesal [xxx]: GET /getUpdates?b=6447&c=1951&d=234824&m=t&q=t 500 1.04s macos/safari/13.1.2

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.LockNotAvailable: canceling statement due to lock timeout
CONTEXT:  while updating tuple (29,156) in relation "useractivity"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/webargs/core.py", line 452, in wrapper
    return func(*new_args, **kwargs)
  File "/service/timApp/lecture/routes.py", line 136, in get_updates
    ret = do_get_updates(m)
  File "/service/timApp/lecture/routes.py", line 235, in do_get_updates
    lecture = get_current_lecture()
  File "/service/timApp/lecture/routes.py", line 761, in get_current_lecture
    lectures: List[Lecture] = u.lectures.all()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3211, in all
    return list(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/dynamic.py", line 304, in __iter__
    sess = self.session
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/dynamic.py", line 295, in session
    sess.flush()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2577, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 230, in save_obj
    _emit_update_statements(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 942, in _emit_update_statements
    c = connection.execute(statement.values(value_params), params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.LockNotAvailable) canceling statement due to lock timeout
CONTEXT:  while updating tuple (29,156) in relation "useractivity"

[SQL: UPDATE useractivity SET active=now() WHERE useractivity.lecture_id = %(useractivity_lecture_id)s AND useractivity.user_id = %(useractivity_user_id)s]
[parameters: {'useractivity_lecture_id': 616, 'useractivity_user_id': 1}]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

Vastaavia poikkeuksia ei ennen ole tullut; tosin tuo lukitusmekanismi lisättiin 10.3.2020, joten se ei ole aivan hirveästi saanut real-world-testausta.

**Comment by dezhidki** [comment]
Duplikaatti:  #1975
