### ISSUE TITLE
Käännöstesti ei mene läpi lokaalissa koneessa

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3356]
tim-tests-1  | 
Error
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: unit.test_translator_generic
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/service/timApp/tests/unit/test_translator_generic.py", line 23, in <module>
    from timApp.tests.server.test_translation import TimTranslationTest
  File "/service/timApp/tests/server/test_translation.py", line 44, in <module>
    class QuotaLimitedTestTranslator(ReversingTranslationService):
  File "/usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/model.py", line 67, in __init__
    super(NameMetaMixin, cls).__init__(name, bases, d)
  File "/usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/model.py", line 121, in __init__
    super(BindMetaMixin, cls).__init__(name, bases, d)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/ext/declarative/api.py", line 76, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/ext/declarative/base.py", line 131, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/ext/declarative/base.py", line 160, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/ext/declarative/base.py", line 192, in __init__
    self._setup_inheritance()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/ext/declarative/base.py", line 609, in _setup_inheritance
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Column 'character_limit' on class <class 'timApp.tests.server.test_translation.QuotaLimitedTestTranslator'> conflicts with existing column 'translationservice.character_limit'

**Comment by dezhidki** [comment]
Tarkennatko, miten ajoit testit ja millä haaralla? Itse en saa toistettua masterilla (Windows ja Linux toimivat myös). Alla vielä kaappaus omasta testauskonffauksesta:

![image](https://user-images.githubusercontent.com/5202606/219947749-1237989d-6780-4a91-80d5-a505bf9e3953.png)


Ja testit siis menevät läpi:

![image](https://user-images.githubusercontent.com/5202606/219947782-6a2f9054-1a5c-4f04-b9b4-ba2f82f9320c.png)

**Comment by vesal** [comment]
![image](https://user-images.githubusercontent.com/826392/219948040-fb8dc02d-b3f6-4074-94c4-9c548ae60c1c.png)

![image](https://user-images.githubusercontent.com/826392/219948051-b85a901f-b6a3-485c-ac68-abb385e90bd8.png)

**Comment by vesal** [comment]
Yksistään ajettuna menee läpi:

![image](https://user-images.githubusercontent.com/826392/219950255-5a0088f1-0429-4f28-b358-93432885ec2b.png)

Mutta ei siinä missä ajaa ne 900 testiä
