### ISSUE TITLE
Areat rikkoi dokumentin kokonaan

### ISSUE THREAD

**Issue by sijualle** [TIM-JYU/TIM#3381]
Jaoin isoa dokumenttia areoihin, jotta sinne voisi laittaa linkkejä joilla näyttää dokumentin valmiiksi paloteltuina.
Yhden ennestään olleen arean nimesin uudestaan käyttäen edit area-painiketta, jonka jälkeen lisäsin kaksi uutta areaa dokumenttiin.

Jostain syystä tuota noille kahdelle uudelle arealle tuli samat nimet ja id:t, vaikka olin mielestäni laittanut niille eri nimet, ja jostain syystä niille generoitui vielä täysin samat id:t. 

Tuota ei saanut korjattua mitenkään timin käyttöliittymästä, sillä view-näkymässä tuli vain 500-viestiä ja managen kauttakin vanhaa versiota liittäessä palvelin ei suostunut päivittämään dokumenttia vaan intti että dokumentin vanhassa versiossa on virheitä.

**Comment by vesal** [comment]
Kansisiko tuosta tehdä kopioi ja koittaa saada siihen kopioon tuota toistettua
niin, että näkisi mikä rikkoo dokumentin noin pahoin?

**Comment by vesal** [comment]
Siellähän oli joku wuff rekursion syvyydestä, ehdin jo tuhota sen, siitä olisi varman nähnyt rivin.

**Comment by sijualle** [comment]
Virhe joka esti dokumentin korjaamisen myös managessa

```
The original document contained a syntax error. This is probably a TIM bug; please report it. Additional information: 
Duplicate paragraph id noticed in paragraph 4tnMpqjf0Wo6
Multiple areas with same name noticed for area 'KuullunB' in paragraph 4tnMpqjf0Wo6
Duplicate paragraph id noticed in paragraph u9ewa1T13LwU
Duplicate area end noticed in paragraph u9ewa1T13LwU
```

name_area lokit

```
[sijualle@xtim]$ tail -n 500000 /opt/tim/tim_logs/timLog.log | grep name_area
2023-04-07 10:12:55,812 INFO: sijualle (x) [x]: POST /name_area/221/KuullunB 200 0.161s windows_10/firefox/107.0 3821
2023-04-07 10:13:25,197 ERROR: Exception on /name_area/221/LuetunA [POST]
  File "/service/timApp/document/editing/routes.py", line 1000, in name_area
2023-04-07 10:13:25,208 ERROR: sijualle (x) [x]: POST /name_area/221/LuetunA 500 0.0876s windows_10/firefox/107.0 3830
2023-04-07 10:13:25,215 INFO: sijualle (x) [x]: POST /name_area/221/LuetunA 500 0.095s windows_10/firefox/107.0 3830
```
name_area LuetunA wuff


```
sijualle (x) [x]: POST /name_area/221/LuetunA 500 0.0876s windows_10/firefox/107.0 3830

{'area_end': 'cbttJkoEtXq7',
 'area_start': 'jSiED02EKtQH',
 'options': {'collapse': True, 'collapsible': False, 'hlevel': 0}}

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/service/timApp/document/editing/routes.py", line 1000, in name_area
    doc.get_named_section(area_name),
  File "/service/timApp/document/document.py", line 1023, in get_named_section
    raise InvalidReferenceException("Area not found: " + section_name)
timApp.timdb.exceptions.InvalidReferenceException: Area not found: LuetunA
```

13:13:25 diffit
https://sukol-koe.tim.education/diff/221/122/0/123/0
https://sukol-koe.tim.education/diff/221/123/0/124/0

Eli jostain syystä tuo 13:13:25/10:13:25 name_area LuetunA ei tehnytkään pyydettyihin paikkoihin aluekappaleita LuetunA, vaan teki niihin kohtiin aluekappaleet KuullunB joissa on samat id:t kuin dokumentissa aiemmin olevilla KuullunB-aluekappaleilla
