### ISSUE TITLE
TIM setup epäonnistuu joillakin Linux-jakeluilla

### ISSUE THREAD

**Issue by saviit** [TIM-JYU/TIM#3449]
Joissakin Linux-jakeluissa (ainakin Arch/Manjaro) on otettu käyttöön [PEP668](https://peps.python.org/pep-0668/), kts. myös <https://bbs.archlinux.org/viewtopic.php?id=286788>. Tämä estää ajamasta TIMin asennus/setup-skriptiä loppuun.

Setupissa pitäisi kaiketi siis oletuksena pakottaa Pythonin virtualenv ja ajaa pip/poetry jne. sieltä.

**Comment by dezhidki** [comment]
Tuleeko siis asennuksen yhteydessä tuo `error: externally-managed-environment`?

Jos sinulla on joku setuppi vielä menossa, niin kokeilisitko ajaa setupin `--verbose` -lipulla eli esim `./tim --verbose setup` ja laittaa tähän korttiin tulosteen? Sillä saisi ehkä alkuun tutkittua, missä ongelma piilee.

**Comment by saviit** [comment]
> Tuleeko siis asennuksen yhteydessä tuo `error: externally-managed-environment`?

Joo, tulee juuri tuo virheilmoitus. En ehtinyt saada tuota toimimaan ennen kuin lähdin reissuun viikonlopuksi niin en ottanut työkonetta matkaan, mutta palaan tähän viimeistään maanantaina kun pääsen taas työkoneen ääreen.

**Comment by saviit** [comment]
```
[samantvi@ruoska tim]$ ./tim --verbose setup --force
[DEBUG] cmd: docker --version
[DEBUG] cmd: docker compose version
--------------------
Which TIM run profile should be used?
Select one of the following based on your needs:

* prod: Run the TIM instance in production mode. All services will be installed and started.
* dev: Run TIM instance in local development mode. Allows you to develop TIM and related services.
* test: Run TIM in CI testing mode. Starts a minimal number of services to speed up testing.
--profile= dev
[INFO] Creating tim.conf
[INFO] Created tim.conf created. Check the config file for more options.
[INFO] Setting up the development environment
[DEBUG] cmd: pip --version
[DEBUG] cmd: python --version
[INFO] Downloading Poetry
[DEBUG] cmd: pip install --upgrade poetry==1.2.1
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
[DEBUG] Traceback (most recent call last):
  File "/opt/tim/cli/tim.py", line 90, in main
    args.run(args)
  File "/opt/tim/cli/commands/setup.py", line 496, in run
    setup_dev()
  File "/opt/tim/cli/commands/setup.py", line 329, in setup_dev
    run_cmd([*pip, "install", "--upgrade", f"poetry=={POETRY_MIN_VERSION}"])
  File "/opt/tim/cli/util/proc.py", line 17, in run_cmd
    return subprocess.run(args, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pip', 'install', '--upgrade', 'poetry==1.2.1']' returned non-zero exit status 1.

[ERROR] Command '['pip', 'install', '--upgrade', 'poetry==1.2.1']' returned non-zero exit status 1.
[samantvi@ruoska tim]$ ls

```

**Comment by dezhidki** [comment]
Okei, joo. No tuossa helpointa on nyt tehdä niin kuin se ehdottaa ja laittaa `--break-system-packages`, koska poetry on kuitenkin tarkoitettu ihan globaaliksi työkaluksi. 

Ideaalisesti olisi kyllä hyvää esimerkiksi setupata .venv, asentaa siihen poetry ja sen jälkeen asentaa loput pakkaukset. Korjaamisen kannalta alkuun parempi saattaa olla käyttää tuota vipua, niin ainakin setup menee läpi.

Puskin tuon vivun käyttöä masteriin, joten tämä on toistaiseksi ratkaistu. Tuota venv-ajatusta pitää kyllä miettiä tarkemmin.

**Comment by saviit** [comment]
Avaan tämän issuen uudelleen. Tuo aikaisempi auttoi nyt Python-pakettien asentamiseen, mutta ongelmia tuli lisää (näistä yhden asennuskripteihin liittyvän jo korjasinkin).

Alla 'lokia', josta näkynee ongelmakohta:

```
[samantvi@ruoska ~]$ curl -sL https://get.tim.education/linux.sh | bash -s - --profile dev
Determined distro: arch
Downloading installation scripts...
Running installation (you will be prompted for your password)...

-- SNIP --

  • Installing types-requests (2.28.11.2)
[INFO] Copying project workspace template
[INFO] Docker: Pulling TIM images

unauthorized: authentication required
[ERROR] Command '['docker', 'compose', '-f', '/opt/tim/docker-compose.yml', 'pull', '--quiet']' returned non-zero exit status 18.

[samantvi@ruoska tim]$ ./tim --verbose setup --force
[DEBUG] cmd: docker --version
[DEBUG] cmd: docker compose version
--------------------
Which TIM run profile should be used?
Select one of the following based on your needs:

* prod: Run the TIM instance in production mode. All services will be installed and started.
* dev: Run TIM instance in local development mode. Allows you to develop TIM and related services.
* test: Run TIM in CI testing mode. Starts a minimal number of services to speed up testing.
--profile= dev

-- SNIP --

[DEBUG] cmd: poetry --version
[INFO] Installing Python development dependencies
[DEBUG] cmd: poetry install --only=dev
Installing dependencies from lock file

No dependencies to install or update
[DEBUG] cmd: /opt/tim/.venv/bin/pip --version
[DEBUG] cmd: /usr/bin/npm --version
[INFO] Project workspace already exists, skipping copying template
[INFO] Docker: Pulling TIM images
[DEBUG] Failed to interpolate COMPOSE_PROJECT_NAME:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROFILES:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROJECT_NAME:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROJECT_NAME:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROFILES:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate SKIP_JSRUNNER_START:-false: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROJECT_NAME:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROJECT_NAME:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROFILES:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate CI:-false: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate NEW_SCREENSHOTS:-0: invalid syntax (<string>, line 1)
[DEBUG] cmd: docker compose -f /opt/tim/docker-compose.yml pull
[+] Pulling 12/23

-- SNIP --

0s  ✔ pali Skipped - Image is already being pulled by fields                                                           0.0s  ✔ timagent Skipped - Image is already being pulled by fields                                                       0.0s  ✔ feedback Skipped - Image is already being pulled by fields                                                       0.0s  ⠼ caddy 4 layers [⠀⠀⠀⠀]      0B/0B      Pulling                                                                  371.4s  ✔ haskellplugins Pulled                                                                                            1.0s  ✔ mailman-test Pulled                                                                                              1.0s  ⠼ redis 6 layers [⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                371.4s  ✔ fields Pulled                                                                                                    1.0s  ✔ maxima Pulled                                                                                                    1.0s  ⠼ showfile 71 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣤⣿⣿⣿⣿⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣿⣿⡀⣿⣿] 551.6MB/1.144GB Pulling 371.4s ck-api-server Pulled                                                                                          1.0s 
 ✔ stack-api-server Pulled                                                                                          1.0s 
 ✔ postgresql-test Pulled                                                                                           1.3s 
 ✔ oiko Pulled                                                                                                      1.0s 
 ✔ dumbo Pulled                                                                                                     1.0s 
unauthorized: authentication required
[DEBUG] Traceback (most recent call last):
  File "/opt/tim/cli/tim.py", line 90, in main
    args.run(args)
  File "/opt/tim/cli/commands/setup.py", line 511, in run
    run_compose(["pull", *dc_pull_args])
  File "/opt/tim/cli/docker/run.py", line 88, in run_compose
    return run_cmd(compose_args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tim/cli/util/proc.py", line 17, in run_cmd
    return subprocess.run(args, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'compose', '-f', '/opt/tim/docker-compose.yml', 'pull']' returned non-zero exit status 18.

[ERROR] Command '['docker', 'compose', '-f', '/opt/tim/docker-compose.yml', 'pull']' returned non-zero exit status 18.

[samantvi@ruoska tim]$ cd cli/util
[samantvi@ruoska util]$ ls
errors.py  hash.py  __init__.py  iter.py  logging.py  monkeypatches.py  proc.py  __pycache__  template.py
[samantvi@ruoska util]$ nano proc.py

-- NOTE --

proc.py: 14, run_cmd

    args: List[str], check: bool = True, **kwargs: Any
--> args: List[str], check: bool = False, **kwargs: Any

-- END NOTE --

[samantvi@ruoska util]$ cd ../..
[samantvi@ruoska tim]$ ./tim --verbose setup --force
[DEBUG] cmd: docker --version
[DEBUG] cmd: docker compose version
--------------------
Which TIM run profile should be used?
Select one of the following based on your needs:

* prod: Run the TIM instance in production mode. All services will be installed and started.
* dev: Run TIM instance in local development mode. Allows you to develop TIM and related services.
* test: Run TIM in CI testing mode. Starts a minimal number of services to speed up testing.
--profile= dev

-- SNIP --

[INFO] Docker: Pulling TIM images
[DEBUG] Failed to interpolate COMPOSE_PROJECT_NAME:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROFILES:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROJECT_NAME:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROJECT_NAME:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROFILES:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate SKIP_JSRUNNER_START:-false: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROJECT_NAME:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROJECT_NAME:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate COMPOSE_PROFILES:?: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate CI:-false: invalid syntax (<string>, line 1)
[DEBUG] Failed to interpolate NEW_SCREENSHOTS:-0: invalid syntax (<string>, line 1)
[DEBUG] cmd: docker compose -f /opt/tim/docker-compose.yml pull
[+] Pulling 17/23
-- SNIP --
[+] Pulling 88/23ipped - Image is already being pulled by fields                                                    0.0s  ✔ celery-beat Skipped - Image is already being pulled by fields                                                    0.0s  ✔ jsrunner Skipped - Image is already being pulled by fields                                                       0.0s  ✔ pali Skipped - Image is already being pulled by fields                                                           0.0s  ✔ tim Skipped - Image is already being pulled by fields                                                            0.0s  ✔ fields Pulled                                                                                                    1.1s  ✔ stack-api-server Pulled                                                                                          1.0s  ✔ haskellplugins Pulled                                                                                            1.0s  ✔ dumbo Pulled                                                                                                     1.0s  ✔ maxima Pulled                                                                                                    1.0s  ✔ oiko Pulled                                                                                                      1.0s  ✔ timagent Skipped - Image is already being pulled by fields                                                       0.0s  ⠴ caddy 4 layers [⠀⠀⠀⠀]      0B/0B      Pulling                                                                  370.6s  ⠴ redis 6 layers [⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                370.6s  ⠴ showfile 71 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣤⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⣿⣿⠀⣿⣿] 355.6MB/868.1MB Pulling 370.6s tgresql Pulled                                                                                                1.3s 
 ✔ postgresql Pulled                                                                                                1.3s 
 ✔ celery Skipped - Image is already being pulled by fields                                                         0.0s 
 ✔ csplugin Skipped - Image is already being pulled by showfile                                                     0.0s 
 ✔ postgresql-test Skipped - Image is already being pulled by postgresql                                            0.0s 
 ✔ imagex Skipped - Image is already being pulled by showfile                                                       0.0s 
 ✔ drag Skipped - Image is already being pulled by fields                                                           0.0s 
 ✔ tests Skipped - Image is already being pulled by fields                                                          0.0s 
 ✔ feedback Skipped - Image is already being pulled by fields                                                       0.0s 
 ✔ mailman-test Pulled                                                                                              1.0s 
unauthorized: authentication required
[INFO] NPM: Installing TIM dependencies
[DEBUG] OS identifier: Linux
[DEBUG] Running npm with args: ['install']; running in docker: True
[DEBUG] cmd: docker compose -f /opt/tim/docker-compose.yml run -T --rm --no-deps --workdir /service/timApp tim npm install

-- SNIP

[INFO] Docker: Starting containers
[DEBUG] cmd: docker compose -f /opt/tim/docker-compose.yml up -d --remove-orphans
[+] Running 23/23
 ✔ Container tim-postgresql-test-1   Started                                                                        1.8s 
 ✔ Container tim-maxima-1            Started                                                                        0.6s 
 ✔ Container tim-mailman-test-1      Started                                                                        0.8s 
 ✔ Container tim-oiko-1              Started                                                                        2.0s 
 ✔ Container tim-fields-1            Started                                                                        1.5s 
 ✔ Container tim-redis-1             Started                                                                        0.9s 
 ✔ Container tim-haskellplugins-1    Started                                                                        1.8s 
 ✔ Container tim-pali-1              Started                                                                        2.2s 
 ✔ Container tim-timagent-1          Started                                                                        1.0s 
 ✔ Container tim-jsrunner-1          Started                                                                        1.2s 
 ✔ Container tim-imagex-1            Started                                                                        1.5s 
 ✔ Container tim-caddy-1             Started                                                                        1.2s 
 ✔ Container tim-showfile-1          Started                                                                        1.9s 
 ✔ Container tim-drag-1              Started                                                                        1.6s 
 ✔ Container tim-dumbo-1             Started                                                                        1.4s 
 ✔ Container tim-tests-1             Started                                                                        2.0s 
 ✔ Container tim-tim-1               Started                                                                        2.7s 
 ✔ Container tim-feedback-1          Started                                                                        2.1s 
 ✔ Container tim-csplugin-1          Started                                                                        2.7s 
 ✔ Container tim-stack-api-server-1  Started                                                                        2.8s 
 ✔ Container tim-postgresql-1        Started                                                                        0.9s 
 ✔ Container tim-celery-1            Started                                                                        3.1s 
 ✔ Container tim-celery-beat-1       Started                                                                        3.1s 
[INFO] TIM is now up and running!
[samantvi@ruoska tim]$ ./tim update all

 -- SNIP --

 ✔ dumbo Pulled                                                                                                                                                                                                                    1.0s 
 ⠹ redis 6 layers [⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                                               372.3s 
 ✔ celery-beat Skipped - Image is already being pulled by drag                                                                                                                                                                     0.0s 
 ✔ tests Skipped - Image is already being pulled by drag                                                                                                                                                                           0.0s 
 ✔ postgresql-test Skipped - Image is already being pulled by postgresql                                                                                                                                                           0.0s 
 ✔ tim Skipped - Image is already being pulled by drag                                                                                                                                                                             0.0s 
 ✔ haskellplugins Pulled                                                                                                                                                                                                           1.0s 
 ✔ feedback Skipped - Image is already being pulled by drag                                                                                                                                                                        0.0s 
 ✔ imagex Skipped - Image is already being pulled by csplugin                                                                                                                                                                      0.0s 
 ✔ fields Skipped - Image is already being pulled by drag                                                                                                                                                                          0.0s 
 ⠹ caddy 4 layers [⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                                                 372.3s 
 ✔ showfile Skipped - Image is already being pulled by csplugin                                                                                                                                                                    0.0s 
 ✔ maxima Pulled                                                                                                                                                                                                                   1.0s 
 ⠹ csplugin 71 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣤⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣿⣿⡀⣿⣿] 408.9MB/868.1MB Pulling                                                                                                          372.3s 
 ✔ stack-api-server Pulled                                                                                                                                                                                                         1.0s 


WARNING: Some service image(s) must be built from source by running:
    docker compose build csplugin
unauthorized: authentication required


[INFO] Updating TIM database
[+] Running 1/1
 ✔ Container tim-postgresql-1  Started                                                                                                                                                                                             0.3s 
[INFO] Updating TIM database
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
[INFO] Updating TIM frontend
[INFO] Running `npm install` to install build dependencies.

-- SNIP --

Build at: 2023-08-08T13:22:19.710Z - Hash: dc06d4a70ae4e3bf - Time: 133291ms
[INFO] Starting everything up
[+] Running 23/23oiko-1              Started                                                                                                                                                                                       0.6s 
 ✔ Container tim-tests-1             Started                                                                                                                                                                                       0.9s 
 ✔ Container tim-imagex-1            Started                                                                                                                                                                                       1.3s 
 ✔ Container tim-fields-1            Started                                                                                                                                                                                       2.3s 
 ✔ Container tim-maxima-1            Started                                                                                                                                                                                       1.7s 
 ✔ Container tim-showfile-1          Started                                                                                                                                                                                       1.4s 
 ✔ Container tim-haskellplugins-1    Started                                                                                                                                                                                       1.9s 
 ✔ Container tim-oiko-1              Started                                                                                                                                                                                       0.6s 
 ✔ Container tim-drag-1              Started                                                                                                                                                                                       1.2s 
 ✔ Container tim-feedback-1          Started                                                                                                                                                                                       0.8s 
 ✔ Container tim-tim-1               Started                                                                                                                                                                                       2.4s 
 ✔ Container tim-postgresql-1        Running                                                                                                                                                                                       0.0s 
 ✔ Container tim-jsrunner-1          Started                                                                                                                                                                                       1.0s 
 ✔ Container tim-postgresql-test-1   Started                                                                                                                                                                                       1.8s 
 ✔ Container tim-timagent-1          Started                                                                                                                                                                                       1.2s 
 ✔ Container tim-redis-1             Started                                                                                                                                                                                       2.3s 
 ✔ Container tim-pali-1              Started                                                                                                                                                                                       0.8s 
 ✔ Container tim-dumbo-1             Started                                                                                                                                                                                       1.7s 
 ✔ Container tim-mailman-test-1      Started                                                                                                                                                                                       0.6s 
 ✔ Container tim-stack-api-server-1  Started                                                                                                                                                                                       2.4s 
 ✔ Container tim-caddy-1             Running                                                                                                                                                                                       0.0s 
 ✔ Container tim-csplugin-1          Started                                                                                                                                                                                       2.1s 
 ✔ Container tim-celery-beat-1       Started                                                                                                                                                                                       3.0s 
 ✔ Container tim-celery-1            Started                                                                                                                                                                                       3.0s 
[samantvi@ruoska tim]$ 
```

**Comment by saviit** [comment]
Tiivistyksenä:

- konttien pullaaminen jää aina kesken n. 370 sekunnin kohdalla. Muutin `proc.py`ssä `check`-argumentin oletuksen Falseksi oletuksena, jolla pääsi eteenpäin prosessia, mutta ei ratkaise perimmäistä ongelmaa
- vaikka prosessin päätteeksi kontit mukamas käynnistetään onnistuneesti, ei kyseessä ole juuri pullatut, vaan dockerissa vanhan asennuksen jäljiltä olleet kontit (TIMin sai käynnistettyä ja kirjautuminen aikaisemmalla tunnuksella onnistui --> pakko olla vanhan kontin tietokanta)
- JS:t saa käännettyä uudelleen `./tim js` komennolla, mutta bdw antaa virheen `EACCES: permission denid, rmdir '/opt/tim/timApp/static/scripts/build/en-US' ja jää jumiin pyörittämään js-käännöksiä ilman tuloksia

Jatkan selvittämistä virtuaalikoneessa täysin puhtaalta pöydältä.

**Comment by dezhidki** [comment]
Kokeiletko ensin omalla koneella ihan

```
docker logout
```

kun sinulla saattaa olla nyt jokin vanhentunut sisäänkirjautuminen. Konttien pullaus pitää onnistua ilman mitään autentikoitumista.

> vaikka prosessin päätteeksi kontit mukamas käynnistetään onnistuneesti, ei kyseessä ole juuri pullatut, vaan dockerissa vanhan asennuksen jäljiltä olleet kontit 

Yrititkö asentaa täysin uudestaan samaan kansioon? Jos joo, niin vanha tietokanta kyllä jää, koska volumet pysyvät. Jos teet uudelleenasennuksen, kannattanee ajaa

```
docker stop $(docker ps -a -q)
docker system prune -a
```

niin se sammuttaa kaikki kontit sekä poistaa kaikki imaget ja volumet. Silloin voit aloittaa täysin tyhältä pöydältä

> JS:t saa käännettyä uudelleen ./tim js komennolla, mutta bdw antaa virheen `EACCES: permission denid, rmdir '/opt/tim/timApp/static/scripts/build/en-US' ja jää jumiin pyörittämään js-käännöksiä ilman tuloksia

Tuossa voisi ekaksi kokeilaa ihan poistaa `/opt/tim/timApp/static/scripts/build` jos sillä on jotain vääriä oikeuksia.

**Comment by saviit** [comment]
> Yrititkö asentaa täysin uudestaan samaan kansioon? Jos joo, niin vanha tietokanta kyllä jää, koska volumet pysyvät. Jos teet uudelleenasennuksen, kannattanee ajaa

Nimesin vanhan `tim`->`tim-old` ennen mitään noita, ja `docker ps` sanoi ettei mitään kontteja ollut silloin käynnissä. En toki muistanut prunettaa noita, eli siinä varmaan meni mönkään.

**Comment by saviit** [comment]
Piti vielä tyhjentää PyCharmin cachet/vanhat roinat (`File -> Invalidate Caches` ja varuulta `Help -> Delete Leftover IDE Directories`), mutta nyt tuntuu toimivan. 

Ennen kuin nuo cachet tyhjensi niin bdw kaatui aina oikeusvirheisiin `/opt/tim/timApp/static/scripts/build` kanssa, jos sen poisti niin kaatui oikeusvirheisiin Angular cachen `/opt/tim/timApp/.angular/cache` kanssa. Jos poisti Angular cachen niin valitti taas `../scripts/build`sta...

Testasin myös täysin puhtaalla asennuksella virtuaalikoneen Manjarossa, ja toimii ok. PyCharm ei tosin meinannut ensin ymmärtää tim-ajokonfiguraatiota oikein (valitti `module timApp not found`), mutta se korjaantui kun kävi Edit configurations... -valikossa tim-koffin kohdalla painamassa Apply ja OK (vaihtamatta asetuksia).
