### ISSUE TITLE
./tim setup kaatuu bugiin vanhassa node-gyp versiossa

### ISSUE THREAD

**Issue by saviit** [TIM-JYU/TIM#3479]
```
[DEBUG] Running npm with args: ['install']; running in docker: True
[DEBUG] cmd: docker compose -f C:/Projects/Repos/tim-jyu/tim/docker-compose.yml run -T --rm --no-deps --workdir /service/timApp/modules/jsrunner/server tim npm install

> isolated-vm@4.4.2 install /service/timApp/modules/jsrunner/server/node_modules/isolated-vm
> node-gyp rebuild --release -j 4

(node:19) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /service/timApp/modules/jsrunner/server/node_modules/isolated-vm
gyp ERR! node -v v16.20.2
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@4.4.2 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isolated-vm@4.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-09-19T10_23_41_209Z-debug.log
[DEBUG] Traceback (most recent call last):
  File "C:\Projects\Repos\tim-jyu\tim\cli\tim.py", line 90, in main
    args.run(args)
  File "C:\Projects\Repos\tim-jyu\tim\cli\commands\setup.py", line 514, in run
    npmi()
  File "C:\Projects\Repos\tim-jyu\tim\cli\commands\npmi.py", line 37, in npmi
    run_npm(["install"], "timApp/modules/jsrunner/server", True)
  File "C:\Projects\Repos\tim-jyu\tim\cli\npm\run.py", line 77, in run_npm
    run_compose(
  File "C:\Projects\Repos\tim-jyu\tim\cli\docker\run.py", line 88, in run_compose
    return run_cmd(compose_args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Repos\tim-jyu\tim\cli\util\proc.py", line 17, in run_cmd
    return subprocess.run(args, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python3.11\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'compose', '-f', 'C:/Projects/Repos/tim-jyu/tim/docker-compose.yml', 'run', '-T', '--rm', '--no-deps', '--workdir', '/service/timApp/modules/jsrunner/server', 'tim', 'npm', 'install']' returned non-zero exit status 1.

[ERROR] Command '['docker', 'compose', '-f', 'C:/Projects/Repos/tim-jyu/tim/docker-compose.yml', 'run', '-T', '--rm', '--no-deps', '--workdir', '/service/timApp/modules/jsrunner/server', 'tim', 'npm', 'install']' returned non-zero exit status 1.

```

katso myös <https://github.com/nodejs/node-gyp/issues/2219>

**Comment by dezhidki** [comment]
Hmm, okei. Huomasin, että tuotannossa on nyt NodeJS 16. Tässä saattaa auttaa jos päivittää ihan vaan LTSään, eli kokeilen sitä.

**Comment by dezhidki** [comment]
Korjattu. Tästä syystä päivitetty uusi Docker-kontti.

Päivitysvaiheet:

1. Poista `timApp/modules/jsrunner/server/node_modules` -kansio
2. Pullaa uusimmat muutokset
3. `./tim update all`
